
services:
  proton-privoxy:
    image: walt3rl/proton-privoxy
    container_name: proton-privoxy
    environment:
      - PVPN_USERNAME=${VPN_USERNAME}
      - PVPN_PASSWORD=${VPN_PASSWORD}
      - PVPN_SERVER=au1.protonvpn.com  # Specify the server name here
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN

  api:
    build:
      dockerfile: ./docker/api/Dockerfile
    depends_on:
      - proton-privoxy
    ports:
      - 9000:8000
    restart: always

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - USER=${TRANS_USERNAME}
      - PASS=${TRANS_PASSWORD}
    volumes:
      - ${TRANS_CONFIG_PATH}:/config
      - ${DOWNLOAD_HOST_PATH}:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped